<?php
/**
 * Keeps queries generated by the firing of an action.
 *
 * @package lucatume\WPBrowser\Iterators\Filters
 */

namespace lucatume\WPBrowser\Iterators\Filters;

use Iterator;

class ActionsQueriesFilter extends QueriesCallerBasedKeepingFilterIterator
{
    /**
     * ClassMethodQueriesFilter constructor.
     *
     * @param Iterator<string> $iterator The iterator to filter.
     * @param string            $action   The action to filter queries by.
     */
    public function __construct(Iterator $iterator, $action)
    {
        parent::__construct($iterator);

        $this->needles = [
            "do_action('{$action}')"
        ];
    }
}
