#!/usr/bin/env php
<?php
/**
 * WPBrowser CLI - deprecated
 * Use the `codecept` original command
 */
include_once 'vendor/autoload.php';

$console = new Symfony\Component\Console\Output\ConsoleOutput();
$console->writeln("<error>The 'wpcept' command has been deprecated with the release of Codeception 2.3 and will be removed.</error>");
$console->writeln("<info>Use the 'codecept' command instead.\n\n</info>");

$codecept = file_exists(__DIR__ . '/codecept') ?
    __DIR__ . '/codecept'  // bin dir
    : __DIR__ . '/vendor/bin/codecept'; // as a dependency

include $codecept;
