#!/usr/bin/env bash

function wpcliCheck(){
	command -v wp >/dev/null 2>&1 || { echo >&2 "wp (wp-cli) is required for the installation to complete.  Aborting."; exit 1; }
}

function dockerComposeCheck(){
	command -v docker-compose >/dev/null 2>&1 || { echo >&2 "docker-compose is required for the installation to complete.  Aborting."; exit 1; }
}

dockerComposeCheck

echo "\nStopping containers...\n"
docker-compose down -v

echo "\nBuilding images...\n"
docker-compose build

echo "\nStarting containers...\n"
docker-compose up -d

# create the www directory if it does not exist
if [[ ! -d ./www  ]]; then
	echo "\nCreating www folder..n"
	mkdir www
fi

# download WordPress if the not available in the www folder
if [[ ! -f ./www/wp-load.php ]]; then
	wpcliCheck
	echo "\nWordPress not found in the www folder. Downloading...\n"
	wp core download
fi

# configure WordPress if not already configured
if [[ ! -f ./www/wp-config.php ]]; then
	wpcliCheck
	echo "\nWordPress is not configured. Configuring...\n"
	wp config create \
		--dbname=wp \
		--dbuser=wp \
		--dbpass=wp \
		--dbhost=mysql.localhost
fi

wpcliCheck

# Install wordpress
if [[ ! $(wp core is-installed --network) ]]; then
	echo "\nInstalling WordPress...\n"
	wp core multisite-install \
		--url=http://wp.localhost \
		--base=/ \
		--subdomains \
		--title=WP \
		--admin_user=admin \
		--admin_password=admin \
		--admin_email=admin@wp.localhost \
		--skip-email
	wp site create --slug=test1
	wp site create --slug=test2
	wp site create --slug=test3
	wp rewrite structure '%postname%' && wp rewrite flush
fi

wp plugin delete akismet hello
mkdir -p www/wp-content/mu-plugins
wp theme delete twentyfifteen twentysixteen
wp site list --field=url | xargs -n1 -I % wp --url=% site empty --yes
wp site list --field=url | xargs -n1 -I % wp --url=% transient delete-all
wp db export ./../tests/_data/dump.sql
