#!/bin/bash
# Runs Codeception commands in the WordPress container project folder

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "$SCRIPTDIR";

if [[ "$OSTYPE" == "darwin"* ]]; then
	COMPOSE="docker-compose"
elif [[ $(which docker.exe) ]]; then
	COMPOSE="docker-compose.exe"
else
	COMPOSE="docker-compose"
fi;

COMMAND="vendor/bin/codecept $@"
# even when running the local stack, for the purpose of this, the CI stack configuration is fine
${COMPOSE} -f stack.yml exec wordpress bash -c "$COMMAND"
