#!/usr/bin/env bash
# Runs a command in the MySQL container

SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "$SCRIPTDIR";

if [[ "$OSTYPE" == "darwin"* ]]; then
	DOCKER="docker"
elif [[ $(which docker.exe) ]]; then
	DOCKER="docker.exe"
else
	DOCKER="docker"
fi;

${DOCKER} run -it --rm \
--volumes-from wpbrowser_db:rw \
--network container:wpbrowser_db \
mysql:5.7 mysql -uroot -proot -h db
