#!/usr/bin/env bash

detectTheSystem(){
    local system=$1
    local os=''

    if [ "Darwin" == $(uname -s) ]; then
        # MacOs
        os="macos"
    elif grep -q Microsoft /proc/version; then
        # bash on ubuntu on Windows
        os="windows"
    else
        # Linux
        os="linux"
    fi

    echo $os
}

getIPAddress(){
    if [ $system == "macos" ]; then
        thisAddress=$(ipconfig getifaddr en0)
        if [ ! $thisAddress ]; then
            thisAddress=$(ipconfig getifaddr en1)
        fi
    else
        thisAddress=$(ip route get 8.8.8.8 | awk '/8.8.8.8/ {print $NF}')
    fi

    echo $thisAddress
}

system=$(detectTheSystem)
address=$(getIPAddress)

echo "System is $system"
echo "Address is $address"

echo "Stopping running Docker containers..."
docker stop $(docker ps -aq) > /dev/null
docker rm $(docker ps -aq) > /dev/null

echo "Starting local containers..."
XDEBUG_REMOTE_HOST=$address docker-compose up
