<?php

namespace tad;


class PublicTestCase extends \PHPUnit_Framework_TestCase
{
	public function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown()
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

}