<?php

namespace tad;

use PHPUnit\Framework\TestCase;

class PublicTestCase extends TestCase {

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

}