ARG PHP_VERSION=5.6
ARG COMPOSER_VERSION=2.2

FROM composer:${COMPOSER_VERSION} AS composer
FROM lucatume/codeception-php-5.6:cc3.1.0-v1.1.1 as php_56_sos
FROM wordpress:php${PHP_VERSION}-apache

ARG USER_UID=33
ARG USER_GID=33
ARG USER_NAME=www-data
ARG TARGET=wordpress

# Install wp-cli
ADD https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar /usr/local/bin/wp
RUN chmod a+rx /usr/local/bin/wp

# Install required extensions, remove the ini file that would enable uopz for Apache: it will be loaded on the
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod a+x /usr/local/bin/install-php-extensions && \
    chmod -R a+rwx /usr/local/etc/php/conf.d && \
    install-php-extensions gd pdo pdo_mysql mysqli zip

# Build XDebug and Uopz for PHP 5.6 from source.
COPY --chmod=0777 php_56_sos/xdebug-2.5.5.tgz /tmp/xdebug-2.5.5.tgz
COPY --chmod=0777 php_56_sos/uopz-2.0.7.tar.gz /tmp/uopz-2.0.7.tar.gz
RUN tar xzf /tmp/xdebug-2.5.5.tgz -C /tmp \
    && mv /tmp/package.xml /tmp/xdebug-2.5.5/package.xml \
    && ls -la /tmp/xdebug-2.5.5 \
    && install-php-extensions /tmp/xdebug-2.5.5 \
    && rm -rf /tmp/xdebug-2.5.5.tgz /tmp/xdebug-2.5.5 \
    && tar xzf /tmp/uopz-2.0.7.tar.gz -C /tmp \
    && install-php-extensions /tmp/uopz-2.0.7 \
    && rm -rf /tmp/uopz-2.0.7.tar.gz /tmp/uopz-2.0.7 \
    && docker-php-ext-enable xdebug \
    && if [ "${TARGET}" = "codeception" ]; then docker-php-ext-enable uopz; fi

# Install required utils
RUN apt-get update && apt-get install -y \
    default-mysql-client curl git zip unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set up PHP defaults
COPY php.ini /usr/local/etc/php/conf.d/999-php-custom.ini
# Make the PHP configuration world-accessible.

# Copy over Composer
COPY --from=composer /usr/bin/composer /usr/local/bin/composer

COPY bashrc_scripts.sh /etc/bashrc_scripts.sh
RUN chmod a+x /etc/bashrc_scripts.sh && echo ". /etc/bashrc_scripts.sh" >> /etc/bash.bashrc
COPY xdebug-on.sh /usr/local/bin/xdebug-on
COPY xdebug-off.sh /usr/local/bin/xdebug-off
RUN chmod a+x /usr/local/bin/xdebug-on && chmod a+x /usr/local/bin/xdebug-off

# Ensure the gropup and user exist.
RUN getent group ${USER_GID} || groupadd -g ${USER_GID} ${USER_NAME}
RUN getent passwd ${USER_UID} || useradd -u ${USER_UID} -g ${USER_GID} -m -s /bin/bash ${USER_NAME}
