name: Automated v3.5 build

on:
  workflow_dispatch: # yamllint disable-line rule:truthy

jobs:
  build_v3_5:
    name: v3.5 Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: "none"
      - name: Validate Composer configuration
        run: composer validate --no-interaction --strict
      - name: Install dependencies
        uses: ramsey/composer-install@v2
      - name: Check PSR-4 mapping"
        run: composer dump-autoload --no-interaction --optimize --strict-psr
      - name: Require rector
        run: composer require --dev rector/rector
      - name: Get changed files
        id: changed-files
        uses: yumemi-inc/changed-files@v3
        with:
          separator: " "
          patterns: |
            src/**/*.php
            includes/**/*.php
            tests/**/*.php
      - name: Build v3.5
        run: |
          vendor/bin/rector process --config=config/rector-35.php -- ${{ steps.changed-files.outputs.files }}
      - name: Create Pull Request on v3.5
        run: |
          git reset HEAD 
          git status
          git add 'src/*.php'
          git add 'includes/*.php'
          git add 'tests/*.php'
          gh pr create \
            --assignee lucatume \
            --base v3.5 \
            --draft \
            --title "v3.5 automated build" \
            --body "v3.5 automated build changes" \
            --label "auto-build" \
            --label "v3.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
